name: windows

on:
    push:
        branches:
            - '*'
        tags-ignore:
            - '*'
        pull_request:

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - windows-2019
                - windows-2016

        steps:
            - uses: actions/checkout@v2
            - name: Set up Perl
              run: |
                choco install strawberryperl
                echo "C:\strawberry\c\bin"         >> $GITHUB_PATH
                echo "C:\strawberry\perl\site\bin" >> $GITHUB_PATH
                echo "C:\strawberry\perl\bin"      >> $GITHUB_PATH
            - name: Perl version
              run: perl -V
            - name: Install dependencies
              run: cpan -M https://www.cpan.org -T .
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
